[project]
name = "wattbot"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "DeianHsu", email = "663781679@qq.com" }
]
requires-python = ">=3.14"
dependencies = [
    "langchain-chroma>=1.1.0",
    "langchain-classic>=1.0.8",
    "langchain-community>=0.4.2",
    "langchain-huggingface>=1.2.2",
    "langchain-openai>=1.6.3",
    "langchain-text-splitters>=1.1.2",
    "pandas>=3.0.6",
    "pypdf>=6.19.0",
    "python-dotenv>=1.2.3",
    "sentence-transformers>=6.1.0",
]

[project.scripts]
wattbot = "wattbot:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
